# Generated by Django 4.2 on 2023-04-22 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('choiceId', models.AutoField(primary_key=True, serialize=False)),
                ('choice', models.CharField(max_length=255)),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.questions')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('answerId', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255)),
                ('questionId', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='trivia.questions')),
            ],
        ),
    ]
